
<?php include('includes/header.php');

    if (isset($_SESSION['username'])) {
       $id =$_SESSION['id'];
    }
    else{
      header("location:login.php");
    } ?>
<link rel="stylesheet" type="text/css" href="css/uni.css">
 <div class="container-fluid px-4">
                   <br><br>
        <br> <h1 style="margin-left:620px;" class="mt-4">About</h1><br>
</div> 

<div class="cont" style="margin-left:270px;">
    <h4>Privacy Policy</h4>
    <p>Last updated: December 16, 2022</p>
    <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
    <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>

    <h3 class="main">Interpretation and Definitions</h3><hr>
    <p style="font-weight: bold;">Interpretation</p>
    <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
    <p style="font-weight: bold;">Definitions</p>
    <p>For the purposes of this Privacy Policy:</p>
    <ul>
        <li>Account - means a unique account created for You to access our Service or parts of our Service.</li>
        <li>Company - (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Lazpee Online Shop.</li>
        <li>Country -  refers to: Philippines</li>
        <li>Personal Data - is any information that relates to an identified or identifiable individual.</li>
        <li>Service - refers to the Website.</li>
        <li>Service Provider - means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
        <li>Usage Data - refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li>Website - refers to Lazpee Online Shop, accessible from http://www.lazpee.com</li>
        <li>You - means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>

    </ul>
    <h3 class="main">Collecting and Using Your Personal Data</h3><hr>
     <p style="font-weight: bolder;">Types of Data Collected</p>
     <p style="font-weight: bold;">Personal Data</p>
     <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
     <p>Email address<br>First name and last name<br>Phone number<br>Address, State, Province, ZIP/Postal code, City<br>Usage Data
</p>
    <p style="font-weight: bold;">Usage Data</p>
    <p>Usage Data is collected automatically when using the Service.</p>
    <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

    <p style="font-weight: bold;">Use of Your Personal Data</p>

    <p>The Company may use Personal Data for the following purposes:</p>
    <ul>
        <li>To provide and maintain our Service: including to monitor the usage of our Service.</li>
        <li>To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.</li>
        <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
        <li>To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.</li>
        <li>To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information</li>
        <li>To manage Your requests: To attend and manage Your requests to Us.</li>
        <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.</li>
        <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
    </ul>

    <p style="font-weight: bold;">We may share Your personal information in the following situations:</p>
    <ul>
        <li>With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.</li>
        <li>For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li>With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li>With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.</li>
        <li>With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.</li>
        <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
    </ul>
    <p style="font-weight: bold;">Business Transactions</p>
    <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
        <p style="font-weight: bold;">Law enforcement</p>
        <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
            <p style="font-weight: bold;">Security of Your Personal Data</p>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

<h3 class="main">Children's Privacy</h3><hr>
<p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
<p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
<h3 class="main">Links to Other Websites</h3><hr>
<p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services</p>

<h3 class="main">Contact Us</h3><hr>
<p>If you have any questions about this Privacy Policy, You can contact us:</p><ul><li>By visiting this page on our website: http://www.lazpee.com</li></ul>
</div>
            
<?php
    include('includes/footer.php');
    include('includes/scripts.php')
?>